version: "3.5"

services:
  db:
    container_name: mariadb
    image: mariadb:10.6
    ports:
      - "3306:3306"

    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: alura
      MARIADB_USER: adriano
      MARIADB_PASSWORD: adriano
